# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

# 设备定义
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 读取训练数据
train_df = pd.read_csv("covid.train.csv")
print("训练集数据形状：", train_df.shape)

# 划分特征和标签
X = train_df.iloc[:, :-1].values
y = train_df.iloc[:, -1].values.reshape(-1, 1)  # 原始标签

# 关键：目标变量做对数变换，适配指数增长
y_log = np.log(y + 1e-6).reshape(-1, 1)

# 特征标准化（和第一次训练一样）
scaler_X = StandardScaler()
X_scaled = scaler_X.fit_transform(X)

# 目标变量（对数后）标准化，让模型更容易训练
scaler_y = StandardScaler()
y_log_scaled = scaler_y.fit_transform(y_log)

# 划分训练/验证集
X_train, X_val, y_train_scaled, y_val_scaled, y_train_original, y_val_original = train_test_split(
    X_scaled, y_log_scaled, y, test_size=0.2, random_state=42
)

print(f"\n训练集大小：{X_train.shape}, 验证集大小：{X_val.shape}")

# 封装数据集（同时保存标准化标签和原始标签）
class CovidDataset(Dataset):
    def __init__(self, x, y_scaled, y_original):
        self.x = torch.tensor(x, dtype=torch.float32)
        self.y_scaled = torch.tensor(y_scaled, dtype=torch.float32)
        self.y_original = y_original

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y_scaled[idx], self.y_original[idx]

batch_size = 32
train_dataset = CovidDataset(X_train, y_train_scaled, y_train_original)
val_dataset = CovidDataset(X_val, y_val_scaled, y_val_original)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

# 模型定义（三层网络 + Dropout=0.5）
class SimpleCovidNet_ReLU(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(16, 1)
        )

    def forward(self, x):
        return self.layers(x)

input_dim = X_train.shape[1]
model_relu = SimpleCovidNet_ReLU(input_dim).to(device)

# 优化器和损失函数
optimizer_relu = optim.Adam(model_relu.parameters(), lr=0.001)
criterion = nn.MSELoss()

# 学习率衰减
from torch.optim.lr_scheduler import ReduceLROnPlateau
scheduler = ReduceLROnPlateau(
    optimizer_relu,
    mode='min',
    factor=0.5,
    patience=10
)

epochs = 200
model_relu.train()

print("开始训练（同时打印标准化尺度和原始人数尺度的Loss）")
for epoch in range(epochs):
    # 训练阶段
    model_relu.train()
    total_train_loss = 0.0
    all_train_pred_scaled = []
    all_train_true_scaled = []
    all_train_pred_original = []
    all_train_true_original = []

    for batch_x, batch_y_scaled, batch_y_original in train_loader:
        batch_x = batch_x.to(device)
        batch_y_scaled = batch_y_scaled.to(device)

        optimizer_relu.zero_grad()
        outputs_scaled = model_relu(batch_x)
        loss = criterion(outputs_scaled, batch_y_scaled)
        loss.backward()
        optimizer_relu.step()

        total_train_loss += loss.item()

        # 保存标准化尺度的预测和真实值
        all_train_pred_scaled.append(outputs_scaled.detach().cpu().numpy())
        all_train_true_scaled.append(batch_y_scaled.cpu().numpy())

        # 还原为原始人数尺度
        outputs_log = scaler_y.inverse_transform(outputs_scaled.detach().cpu().numpy())
        outputs_original = np.exp(outputs_log)
        all_train_pred_original.append(outputs_original)
        all_train_true_original.append(batch_y_original.numpy())

    # 验证阶段
    model_relu.eval()
    total_val_loss = 0.0
    all_val_pred_scaled = []
    all_val_true_scaled = []
    all_val_pred_original = []
    all_val_true_original = []

    with torch.no_grad():
        for batch_x, batch_y_scaled, batch_y_original in val_loader:
            batch_x = batch_x.to(device)
            batch_y_scaled = batch_y_scaled.to(device)

            outputs_scaled = model_relu(batch_x)
            val_loss = criterion(outputs_scaled, batch_y_scaled)
            total_val_loss += val_loss.item()

            # 保存标准化尺度的预测和真实值
            all_val_pred_scaled.append(outputs_scaled.cpu().numpy())
            all_val_true_scaled.append(batch_y_scaled.cpu().numpy())

            # 还原为原始人数尺度
            outputs_log = scaler_y.inverse_transform(outputs_scaled.cpu().numpy())
            outputs_original = np.exp(outputs_log)
            all_val_pred_original.append(outputs_original)
            all_val_true_original.append(batch_y_original.numpy())

    # 合并结果，计算两种尺度的MSE
    # 1. 标准化尺度（和第一次训练同尺度）
    train_pred_scaled = np.concatenate(all_train_pred_scaled, axis=0)
    train_true_scaled = np.concatenate(all_train_true_scaled, axis=0)
    val_pred_scaled = np.concatenate(all_val_pred_scaled, axis=0)
    val_true_scaled = np.concatenate(all_val_true_scaled, axis=0)

    avg_train_loss_scaled = mean_squared_error(train_true_scaled, train_pred_scaled)
    avg_val_loss_scaled = mean_squared_error(val_true_scaled, val_pred_scaled)

    # 2. 原始人数尺度（还原后的真实误差）
    train_pred_original = np.concatenate(all_train_pred_original, axis=0)
    train_true_original = np.concatenate(all_train_true_original, axis=0)
    val_pred_original = np.concatenate(all_val_pred_original, axis=0)
    val_true_original = np.concatenate(all_val_true_original, axis=0)

    avg_train_loss_original = mean_squared_error(train_true_original, train_pred_original)
    avg_val_loss_original = mean_squared_error(val_true_original, val_pred_original)
    avg_val_rmse_original = np.sqrt(avg_val_loss_original)  # 还原RMSE，更直观

    # 更新学习率
    scheduler.step(total_val_loss / len(val_loader))

    # 每10轮打印一次，同时输出两种尺度的Loss
    if (epoch + 1) % 10 == 0:
        current_lr = optimizer_relu.param_groups[0]['lr']
        print(f"Epoch [{epoch+1}/{epochs}] | "
              f"训练Loss(标准化): {avg_train_loss_scaled:.4f} | "
              f"验证Loss(标准化): {avg_val_loss_scaled:.4f} | "
              f"训练Loss(原始人数): {avg_train_loss_original:.2f} | "
              f"验证Loss(原始人数): {avg_val_loss_original:.2f} | "
              f"验证RMSE(原始人数): {avg_val_rmse_original:.2f} | "
              f"当前LR: {current_lr:.6f}")


# ===================== 用训练好的模型测试 test 数据 + 核对样本数量 =====================
# 1. 读取测试数据
test_df = pd.read_csv("covid.test.csv")
X_test = test_df.values

# 打印 test 原始样本数量
print(f"测试集 test.csv 原始样本数量：{len(test_df)} 个")

# 2. 和训练集一样做特征标准化
X_test = scaler_X.transform(X_test)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32).to(device)

# 3. 模型预测（输出是 对数标准化空间）
model_relu.eval()
with torch.no_grad():
    y_pred_scaled = model_relu(X_test_tensor).cpu().numpy()

# 4. 先反标准化回到 log(y) 空间
y_pred_log = scaler_y.inverse_transform(y_pred_scaled)

# 5. 再 exp 还原成真实确诊人数
y_pred_original = np.exp(y_pred_log)

# 6. 生成和 sampleSubmission 格式一样的提交文件
sub = pd.read_csv("sampleSubmission.csv")
print(f"sampleSubmission.csv 里待预测样本数量：{len(sub)} 个")

# 核对数量
print(f"模型实际预测出的结果数量：{len(y_pred_original)} 个")

if len(test_df) == len(sub) == len(y_pred_original):
  print("正在结合模型计算")
else:
    print("警告：样本数量不匹配！")

# 写入预测结果
sub.iloc[:, 1] = y_pred_original
sub.to_csv("covid_submit_final.csv", index=False)

print("\n测试集预测完成，已生成：covid_submit_final.csv")
print("文件生成位置：和你的 covid.train.csv / covid.test.csv 同一文件夹")
